project:
  type: website
  output-dir: publish

toc: true
website:
  title: "Tian's blog"
  navbar:
    background: light
    foreground: black
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tian-lt-personal
format:
  html:
    theme: lumen
    css: styles.css
